### ISSUE TITLE
rollup couldn't resolve typescript file without extension and couldn't compile file either.

### ISSUE THREAD

**Issue by Orenbek** [rollup/plugins#1055]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version:8.3.0
- Rollup Version:2.60.1
- Operating System (or Browser):MacOS
- Node Version: v12.18.0
- Link to reproduction _(⚠️ read below)_: https://replit.com/@Orenbek/rollup-plugin-repro#rollup.config.js

### Expected Behavior
compile ts file currectly.

### Actual Behavior
could resolve .ts file without extension. In addition, even though I give it .ts extension manually, it also couldn't compile typescript file.
`
./src/index.ts → ./lib...
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/demo.ts (1:7)
1: export type Type = {
          ^
2:   name: 'demo'
3: }
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/runner/rollup-plugin-repro/node_modules/rollup/dist/shared/rollup.js:158:30)
    at Module.error (/home/runner/rollup-plugin-repro/node_modules/rollup/dist/shared/rollup.js:12382:16)
    at Module.tryParse (/home/runner/rollup-plugin-repro/node_modules/rollup/dist/shared/rollup.js:12785:25)
    at Module.setSource (/home/runner/rollup-plugin-repro/node_modules/rollup/dist/shared/rollup.js:12688:24)
    at ModuleLoader.addModuleSource (/home/runner/rollup-plugin-repro/node_modules/rollup/dist/shared/rollup.js:22161:20)
`

**Comment by dnalborczyk** [comment]
@Orenbek `plugins` must be in the root of the `rollup config`. you added it as part of "output".
