### ISSUE TITLE
CI Build Failure

### ISSUE THREAD

**Issue by cutterbl** [rollup/plugins#1079]
When building my package locally, I have no issues at all. But, when I push my code to TeamCity, and it attempts to build (exact same process) I get the following error.

```
15:12:37     [!] (plugin babel) Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/plugins/issues. Thanks!
15:12:37     src\index.js
15:12:37     Error: An unexpected situation arose. Please raise an issue at https://github.com/rollup/plugins/issues. Thanks!
15:12:37         at error (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\rollup\dist\shared\rollup.js:158:30)
15:12:37         at throwPluginError (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\rollup\dist\shared\rollup.js:21831:12)
15:12:37         at Object.error (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\rollup\dist\shared\rollup.js:22536:20)
15:12:37         at Object.error (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\rollup\dist\shared\rollup.js:22008:42)
15:12:37         at preflightCheck (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\@rollup\plugin-babel\dist\index.js:228:7)
15:12:37         at D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\@rollup\plugin-babel\dist\index.js:440:13
15:12:37         at transformCode (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\@rollup\plugin-babel\dist\index.js:245:24)
15:12:37         at transform (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\rollup\dist\shared\rollup.js:21978:16)
15:12:37         at ModuleLoader.addModuleSource (D:\TeamCity\install\buildAgent\work\ea77400d8c4ec791\node_modules\rollup\dist\shared\rollup.js:22202:30)
```

- Rollup Plugin Name: @rollup/plugin-babel
- Rollup Plugin Version: 5.3.0
- Rollup Version: 2.63.0
- Operating System (or Browser): ? (I think our Team City environment uses Windows)
- Node Version: 16.13.1
- Link to reproduction _(⚠️ read below)_:

Reproduction: I would love to. But, it's a private repo using a private package manager on corporate servers behind a firewall. The best I'm allowed to do is show you my configuration and answer any questions you might have.

The error message in CI give me nothing more than what you see above. This was a process that was working fine in all environments until I updated packages (all rollup and babel packages). Now I am fine locally (MacOs, same Node version), but get the odd failure message (above) in TeamCity.

### Expected Behavior
For it to build in all environments the same way

### Actual Behavior
Cryptic and uninformative error when building in CI environment

### Additional Information

rollup.config.js
```js
import path from 'path';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import babel from '@rollup/plugin-babel';
import clear from 'rollup-plugin-clear';
import eslint from '@rollup/plugin-eslint';
import cleanup from 'rollup-plugin-cleanup';
import json from '@rollup/plugin-json';
import postcss from 'rollup-plugin-postcss';
import pkg from '../package.json';

const externalDependencies = Object.keys(pkg.dependencies).map((id) =>
  // must do this to  avoid compiling runtime's nested paths
  id.includes('@babel/runtime-corejs3') ? /@babel\/runtime-corejs3/ : id
);

export default [
  {
    input: path.join(__dirname, '../src/app.js'),
    context: 'this',
    output: [
      {
        file: pkg.module,
        format: 'es',
        sourcemap: true,
        exports: 'named',
      },
      {
        file: pkg.main,
        format: 'cjs',
        sourcemap: true,
        exports: 'named',
      },
    ],
    plugins: [
      clear({
        targets: [path.join(__dirname, '../dist')],
        watch: true,
      }),
      postcss({
        exclude: ['src/**/*.module.scss'],
        minimize: true,
        inject: true,
        sourceMap: true,
        config: {
          path: path.join(__dirname, './configs/postcss.config.js'),
        },
      }),
      postcss({
        modules: true,
        include: ['src/**/*.module.scss'],
        minimize: true,
        inject: true,
        sourceMap: true,
        config: {
          path: path.join(__dirname, './configs/postcss.config.js'),
        },
      }),
      resolve({
        // only include local code (imports that begin with './' and '../') in the bundle
        //only: [/^\.{0,2}\//],
        browser: true,
      }),
      commonjs({
        include: ['node_modules/**'],
      }),
      json(),
      eslint({
        // second entry covers 'npm link' situations
        exclude: [/node_modules/, /.scss$/],
      }),
      babel({
        babelHelpers: 'runtime',
        exclude: ['/node_modules/**'],
      }),
      cleanup(),
    ],
    external: externalDependencies,
  },
];
```

package.json
```json
{
  "name": "@ourdomain/scheduler",
  "version": "0.0.27",
  "main": "dist/scheduler.js",
  "module": "dist/scheduler.es.js",
  "engines": {
    "node": ">=16.13.1"
  },
  "license": "LicenseRef-LICENSE",
  "publishConfig": {
    "registry": "http://nexus.ourdomain.com/repository/npm-libraries/"
  },
  "repository": {
    "type": "git",
    "url": "http://gitserver.ourdomain.com/ourdomain/scheduler.git"
  },
  "homepage": "http://gitserver.ourdomain.com/ourdomain/scheduler.git",
  "scripts": {
    "i18n": "i18next-scanner --config ./configs/i18next-scanner.config.js",
    "copyScannerConfig": "copyfiles -f ./src/i18n/i18nScannerConfig.function.js dist/",
    "build": "npm run rollup && npm run copyScannerConfig && npm run i18n -- --output ./dist",
    "test": "npm run i18n -- --output ./dist && cross-env NODE_ENV=test jest",
    "coverage": "npm run i18n -- --output ./dist && cross-env NODE_ENV=test jest --coverage",
    "start": "npm run i18n -- --output ./storyresources && cross-env NODE_ENV=development start-storybook -p 9002 -c .storybook -s ./node_modules,./storyresources",
    "release": "standard-version",
    "rollup": "cross-env NODE_ENV=development rollup -c ./configs/rollup.config.js",
    "prettier": "prettier --write 'src/**/*.js'",
    "reset": "rm package-lock.json && rm -rf node_modules/ && npm i -f",
    "clearPkgs": "node ./scripts/fresh.js",
    "fresh": "npm run clearPkgs && npm run setup",
    "write-npmrc": "node ./scripts/writeNpmRcFile.js",
    "setup": "npm run write-npmrc && npm run build && npm link"
  },
  "dependencies": {
    "@babel/runtime-corejs3": "7.16.7",
    "@ourdomain/components": "*",
    "@ourdomain/core": "*",
    "acorn": "6.1.1",
    "classnames": "2.3.1",
    "font-awesome": "4.7.0",
    "i18next": "21.6.2",
    "i18next-browser-languagedetector": "6.1.2",
    "i18next-intervalplural-postprocessor": "3.0.0",
    "i18next-scanner": "3.1.0",
    "i18next-xhr-backend": "3.2.2",
    "moment": "2.29.1",
    "moment-timezone": "0.5.34",
    "prop-types": "15.8.0",
    "prop-types-extra": "1.1.1",
    "react": "17.0.2",
    "react-big-calendar": "0.38.3",
    "react-dnd": "10.0.2",
    "react-dnd-html5-backend": "10.0.2",
    "react-dom": "17.0.2",
    "react-i18next": "11.15.1",
    "react-overlays": "2.1.0",
    "react-popper": "1.3.7"
  },
  "devDependencies": {
    "@babel/core": "7.16.7",
    "@babel/plugin-transform-runtime": "7.16.7",
    "@babel/preset-env": "7.16.7",
    "@commitlint/cli": "16.0.1",
    "@commitlint/config-conventional": "16.0.0",
    "@ourdomain/uitesting": "0.0.64",
    "@rollup/plugin-babel": "5.3.0",
    "@rollup/plugin-commonjs": "21.0.1",
    "@rollup/plugin-eslint": "8.0.1",
    "@rollup/plugin-json": "4.1.0",
    "@rollup/plugin-node-resolve": "13.1.2",
    "@rollup/plugin-replace": "3.0.1",
    "@storybook/addon-actions": "6.4.9",
    "@storybook/addon-essentials": "6.4.9",
    "@storybook/addon-jest": "6.4.9",
    "@storybook/addon-links": "6.4.9",
    "@storybook/addon-postcss": "2.0.0",
    "@storybook/preset-scss": "1.0.3",
    "@storybook/react": "6.4.9",
    "@storybook/theming": "6.4.9",
    "@testing-library/jest-dom": "5.16.1",
    "@testing-library/react": "12.1.2",
    "autoprefixer": "10.4.1",
    "babel-eslint": "10.1.0",
    "babel-jest": "27.4.5",
    "babel-loader": "8.2.3",
    "babel-preset-react-app": "10.0.1",
    "bootstrap-sass": "3.4.1",
    "chalk": "4.1.0",
    "copyfiles": "2.4.1",
    "core-js": "3.20.2",
    "cross-env": "7.0.3",
    "css-loader": "5.2.6",
    "element-closest-polyfill": "1.0.4",
    "enzyme": "3.11.0",
    "enzyme-adapter-react-16": "1.15.6",
    "eslint": "8.4.1",
    "eslint-config-keystone": "3.0.0",
    "eslint-config-keystone-react": "1.0.0",
    "eslint-config-prettier": "8.3.0",
    "eslint-config-react-app": "7.0.0",
    "eslint-plugin-css-modules": "2.11.0",
    "eslint-plugin-flowtype": "8.0.3",
    "eslint-plugin-import": "2.25.3",
    "eslint-plugin-jsx-a11y": "6.5.1",
    "eslint-plugin-react": "7.27.1",
    "eslint-plugin-react-hooks": "4.3.0",
    "expect": "27.4.2",
    "file-loader": "6.2.0",
    "git-branch-is": "4.0.0",
    "husky": "4.3.8",
    "identity-obj-proxy": "3.0.0",
    "jest": "27.4.5",
    "jest-enzyme": "7.1.2",
    "jest-mock": "27.4.2",
    "jest-mock-axios": "4.5.0",
    "jest-runner-eslint": "1.0.0",
    "jest-teamcity-reporter": "0.9.0",
    "json": "11.0.0",
    "json-loader": "0.5.7",
    "ncp": "2.0.0",
    "postcss": "8.4.5",
    "postcss-assets": "6.0.0",
    "postcss-loader": "6.2.1",
    "prettier": "2.5.1",
    "react-axe": "3.5.4",
    "react-bootstrap": "1.4.3",
    "react-is": "17.0.1",
    "regenerator-runtime": "0.13.9",
    "resolve-url-loader": "4.0.0",
    "rollup": "2.63.0",
    "rollup-plugin-cleanup": "3.2.1",
    "rollup-plugin-clear": "2.0.7",
    "rollup-plugin-postcss": "4.0.2",
    "sass": "1.44.0",
    "sass-loader": "10.1.1",
    "standard-version": "9.3.2",
    "style-loader": "2.0.0"
  },
  "resolutions": {
    "i18next-scanner/**/acorn": "6.1.1"
  }
}
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   🚨 Issues WITHOUT a valid reproduction WILL BE CLOSED!
> 
>   Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      Please use NPM for installing dependencies!
>      These may take more time to triage than the other options.
>   3. Using the Rollup REPL at https://rollupjs.org/repl/
> 
>   ⚠️ ZIP Files are unsafe and maintainers will NOT download them.

We cannot make this any clearer. Please add a reproduction and we'll be happy to triage further.

**Comment by ViRybalkin** [comment]
i have the same problem, maybe someone know how to solve it

**Comment by cutterbl** [comment]
For anyone running into this, and to break it down a little further

- local dev is on MacOS
- ci is in a Windows environment
- to get it working in ci I had to add `skipPreflightCheck: true` to the plugin config (not ideal, but it worked)
