### ISSUE TITLE
[@rollup/plugin-typescript] Plugin resolves asset filename to relative path

### ISSUE THREAD

**Issue by tscpp** [rollup/plugins#1137]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 8.3.1
- Rollup Version: 2.70.1
- Operating System (or Browser): Windows 11/Chrome
- Node Version: 16.13.1
- Link to reproduction: https://replit.com/@EliasSkogevall/rollup-plugin-typescript-repl-2

### Expected Behavior
I except the JavaScript build files to be generated to `dist/` and the Typescript declaration files to be generated to `types/`.

### Actual Behavior
The plugin tries to outsmart me by resolving a relative path to the declaration output using the tsconfig's directory. However, this is a problem because:
1. the declarations will not end up where I told it to.
2. the asset output filename will be relative, which is not allowed.

### Additional Information
Instead of resolving the path at all, as the error suggests ("must be strings that are neither absolute nor relative paths"), pass the output directory path as is.

```
./src/main.ts → ./dist/main.js...
[!] (plugin typescript) Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../types/main.d.ts".
Error: The "fileName" or "name" properties of emitted files must be strings that are neither absolute nor relative paths, received "../types/main.d.ts".
    at error (C:\Users\elias\Desktop\tscpp\rollup-plugin-typescript-repl\node_modules\rollup\dist\shared\rollup.js:198:30)
    at FileEmitter.emitFile (C:\Users\elias\Desktop\tscpp\rollup-plugin-typescript-repl\node_modules\rollup\dist\shared\rollup.js:15513:24)
    at C:\Users\elias\Desktop\tscpp\rollup-plugin-typescript-repl\node_modules\@rollup\plugin-typescript\dist\index.js:816:26
    at Array.forEach (<anonymous>)
    at C:\Users\elias\Desktop\tscpp\rollup-plugin-typescript-repl\node_modules\@rollup\plugin-typescript\dist\index.js:808:37
    at Array.forEach (<anonymous>)
    at Object.generateBundle (C:\Users\elias\Desktop\tscpp\rollup-plugin-typescript-repl\node_modules\@rollup\plugin-typescript\dist\index.js:806:37)
    at C:\Users\elias\Desktop\tscpp\rollup-plugin-typescript-repl\node_modules\rollup\dist\shared\rollup.js:22779:37
```
```javascript
import typescript from '@rollup/plugin-typescript';

export default {
  input: './src/main.ts',
  output: {
    file: './dist/main.js',
    format: 'cjs',
  },
  plugins: [
    typescript({
      declaration: true,
      declarationDir: './types',
    }),
  ],
};
```

**Comment by tscpp** [comment]
I am aware that the plugin option `outDir` or rollup option `output.dir` both work as a workaround. It took me some time to figure this out 😅

**Comment by tscpp** [comment]
As a workaround, you can specify `declarationDir` to the same same directory as the tsconfig and append `/types`.
```javascript
typescript({
  tsconfig: 'src/mod1/tsconfig.json',
  declaration: true,
  // Output will be located at 'types/'
  declarationDir: 'src/mod1/types',
})
```
