### ISSUE TITLE
`@rollup/plugin-node-resolve` version 14.x or 15.x breaks with `rollup-plugin-esbuild`

### ISSUE THREAD

**Issue by MathiasWP** [rollup/plugins#1316]
- Rollup Plugin Name: `@rollup/plugin-node-resolve` and `rollup-plugin-esbuild`
- Rollup Plugin Version: `@rollup/plugin-node-resolve` == 14.x or 15x | `rollup-plugin-esbuild` == latest
- Rollup Version: `2.79` (`rollup-plugin-esbuild` does not support rollup 3)
- Operating System (or Browser): macOS Monterey v12.6
- Node Version: v18.9.0
- Link to reproduction _(⚠️ read below)_: https://github.com/MathiasWP/rollup-esbuild-node-resolve-bug

### Expected Behavior
I think the bug is that it should correctly import files based on the exports in the package json in the library. Downgrade `@rollup/plugin-node-resolve` to version 13.x to see expected behaviour.

### Actual Behavior
<img width="854" alt="Screenshot 2022-10-12 at 17 57 18" src="https://user-images.githubusercontent.com/48158184/195391292-7825662b-bbd2-4301-a097-0ccf213b977b.png">

**Comment by Azarattum** [comment]
I get a similar issue when trying to use `@rollup/plugin-node-resolve` `v14`/`v15` with `vite`.
```
error during build:
Error: 'stdout' is not exported by __vite-browser-external:node:process, imported by status/log.ts
    at error (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at FunctionScope.findVariable (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at MemberExpression.bind (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:8601:49)
    at CallExpression.bind (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
    at CallExpression.bind (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:8935:15)
    at ExpressionStatement.bind (file:///C:/Users/Azarattum/Desktop/Amadeus/node_modules/.pnpm/rollup@2.79.1/node_modules/rollup/dist/es/shared/rollup.js:5269:23)
 ELIFECYCLE  Command failed with exit code 1.
```

Version `13.x` works just fine. 

My `vite.config.js`:
```js
import { nodeResolve } from "@rollup/plugin-node-resolve";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [{ ...nodeResolve(), enforce: "pre" }],
  build: {
    lib: {
      formats: ["cjs"],
      entry: "./app.ts",
    },
  },
});
```
