### ISSUE TITLE
commonjs plugin errors on hashbangs

### ISSUE THREAD

**Issue by privatenumber** [rollup/plugins#1602]
- Rollup Plugin Name:  @rollup/plugin-commonjs
- Rollup Plugin Version:": 25.0.4
- Rollup Version: 3.7.5
- Operating System (or Browser): macOS/StackBlitz
- Node Version: 18.18.0
- Link to reproduction _(⚠️ read below)_: https://stackblitz.com/edit/rollup-repro-cieydd?file=src%2Fmain.js

### Expected Behavior
For it to ignore the hash bang, as Rollup does without the `commonjs` plugin.

### Actual Behavior

Errors:
```
[!] (plugin commonjs--resolver) RollupError: Unexpected character '!'
src/main.js (1:0)
1: #! /usr/bin/env node
   ^
2: 
3: module.exports = 1;
    at error (/home/projects/rollup-repro-cieydd/node_modules/rollup/dist/shared/rollup.js:210:30)
    at Module.error (/home/projects/rollup-repro-cieydd/node_modules/rollup/dist/shared/rollup.js:13498:16)
    at Module.tryParse (/home/projects/rollup-repro-cieydd/node_modules/rollup/dist/shared/rollup.js:13875:25)
    at Module.setSource (/home/projects/rollup-repro-cieydd/node_modules/rollup/dist/shared/rollup.js:13784:24)
    at ModuleLoader.addModuleSource (/home/projects/rollup-repro-cieydd/node_modules/rollup/dist/shared/rollup.js:23216:20)
```

**Comment by privatenumber** [comment]
Relevant issue:
https://github.com/rollup/rollup-plugin-commonjs/issues/261
