### ISSUE TITLE
[@rollup/plugin-commonjs] Uncaught TypeError: utils.Buf8 is not a constructor at strings.js:27:16 in pako

### ISSUE THREAD

**Issue by JamesWilmot** [rollup/plugins#1671]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 25.0.7
- Rollup Version: 4.9.6
- Operating System (or Browser): google-chrome-stable on NixOS (I use Nix btw)
- Node Version: 18.19.0 (version pulled in by flake.nix)
- Link to reproduction _(⚠️ read below)_: https://github.com/JamesWilmot/pako-rollupCommonJSplugin-reproduction

### Expected Behavior

Run ```npm start``` and navigate to ```http://localhost:8000/dummy```. plugin-commonjs 'compiles' [pako](https://github.com/nodeca/pako) UMD module into es6.

### Actual Behavior

google-chrome reports following in console:
```
strings.js:27 Uncaught TypeError: utils.Buf8 is not a constructor
    at strings.js:27:16
```
in ```/node_modules/pako/lib/utils/strings.js```

**Comment by shellscape** [comment]
Thanks for the issue. Unfortunately your reproduction doesn't meet the criteria for minimal. Please see the link in the issue template for guidance and try again, or we can convert this to a Q & A discussion.
