### ISSUE TITLE
[@rollup/plugin-commonjs] engine-v8-version.js:25 Uncaught TypeError: userAgent.match is not a function at engine-v8-version.js:25:21 in core-js

### ISSUE THREAD

**Issue by JamesWilmot** [rollup/plugins#1672]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 25.0.7
- Rollup Version: 4.9.6
- Operating System (or Browser): google-chrome-stable on NixOS (I use Nix btw)
- Node Version: 18.19.0 (version pulled in by flake.nix)
- Link to reproduction _(⚠️ read below)_: https://github.com/JamesWilmot/corejs-rollupCommonJSplugin-reproduction

### Expected Behavior

Run ```npm start``` and navigate to ```http://localhost:8000/dummy```. plugin-commonjs 'compiles' https://github.com/zloirock/core-js UMD module into es6.

### Actual Behavior

google-chrome reports following in console:
```
Uncaught TypeError: userAgent.match is not a function
    at engine-v8-version.js:25:21
```

in ```/node_modules/core-js/internals/engine-v8-version.js```

**Comment by andre487** [comment]
I have the same error

**Comment by shellscape** [comment]
@CharlieHelps please triage this issue

**Comment by shellscape** [comment]
@CharlieHelps please triage this issue
