### ISSUE TITLE
[@rollup/plugin-eslint] New flat config `eslint.config.js` is not recognized

### ISSUE THREAD

**Issue by chkosoptim** [rollup/plugins#1708]
- Rollup Plugin Name: @rollup/plugin-eslint
- Rollup Plugin Version: 9.0.5
- Rollup Version: 4.14.3
- Operating System (or Browser): Windows 10
- Node Version: 20.12.2
- Link to reproduction: https://replit.com/@christiankoch2/rollup-eslint-config-not-found

### Expected Behavior
The plugin should recognize and work with the new flat config (default since ESLint 9.0.0) `eslint.config.js`.

### Actual Behavior
Running `npx rollup --config` yields:
```
[!] (plugin eslint) Error: No ESLint configuration found in <PATH>\src.
src/handler.ts
    at CascadingConfigArrayFactory._finalizeConfigArray (<PATH>\node_modules\@rollup\plugin-eslint\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:521:19)  
    at CascadingConfigArrayFactory.getConfigArrayForFile (<PATH>\node_modules\@rollup\plugin-eslint\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:312:21) 
    at CLIEngine.isPathIgnored (<PATH>\node_modules\@rollup\plugin-eslint\node_modules\eslint\lib\cli-engine\cli-engine.js:1000:18)
    at ESLint.isPathIgnored (<PATH>\node_modules\@rollup\plugin-eslint\node_modules\eslint\lib\eslint\eslint.js:681:26)
    at Object.transform (file:///<PATH>/node_modules/@rollup/plugin-eslint/dist/es/index.js:24:54)
    at <PATH>\node_modules\rollup\dist\shared\rollup.js:989:40
```

### Additional Information
original `rollup.config.js` (no difference if other plugins are removed):
```
import commonjs from '@rollup/plugin-commonjs'
import typescript from 'rollup-plugin-typescript2'
import eslint from '@rollup/plugin-eslint'
import resolve from '@rollup/plugin-node-resolve'
import json from '@rollup/plugin-json'

export default {
  input: 'src/handler.ts',
  output: {
    dir: 'dist/cjs',
    format: 'cjs'
  },
  plugins: [
    json(),
    commonjs(),
    resolve(),
    eslint({ throwOnError: true, fix: true }),
    typescript({ useTsconfigDeclarationDir: true })
  ]
}
```

**Comment by ribeiroguilherme** [comment]
Is there any workaround for this for the time being?

**Comment by manferlo81** [comment]
I use the "overrides" entry on `package.json`, You have to edit it every time you update `eslint` but it works. The problem is @rollup/plugin-eslint is using eslint@8, the "overrides" entry will force eslint to be whatever version you set there.

```json
{
  "overrides": {
    "eslint": "^9.9.0"
  }
}
```

**Comment by Tardo** [comment]
@manferlo81 nice!

I have it like this:
```json
"overrides": {
  "@rollup/plugin-eslint": {
    "eslint": "^9.9"
  }
},
```

**Comment by gabor-at-reed** [comment]
I've tried the "overrides" trick in the `package.json`, but it doesn't work - neither @Tardo 's one nor @manferlo81 's one.

I have `eslint@9.16.0` installed and use `eslint.config.mjs` config file. 

I tried to rename it to `eslint.config.js`, but still no luck... the error is the same:
`[!] (plugin eslint) Error: No ESLint configuration found in <PATH>\src.`

**Comment by liihuu** [comment]
@gabor-at-reed using `pnpm` still doesn't work.

**Comment by dvirtz** [comment]
Using `yarn`
```
  "resolutions": {
    "@rollup/plugin-eslint/eslint": "^9.9.1"
  },
 ```

**Comment by rsenna** [comment]
Thank y'all for the help. Works like a charm.

I do worry that `@rollup/plugin-eslint` does not directly support eslint 9 yet, though.
Some colleagues were considering migrating from webpack to rollup, but support to eslint 9 is required.

But this workaround is good enough for my personal project. Again, thanks.

**Comment by shellscape** [comment]
I've honestly never understood why people run this plug-in as part of the build pipeline. everything I set up runs eslint before builds even begin.
