### ISSUE TITLE
How to tell `--configPlugin` to use specific `tsconfig`?

### ISSUE THREAD

**Issue by JoshMcCullough** [rollup/plugins#1713]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 11.1.5

Documentation Is:

- [ ] Missing
- [ ] Needed
- [ ] Confusing
- [x] Not Sure?

### Please Explain in Detail...

I am getting the error:
>[!] (plugin typescript) RollupError: [plugin typescript] @rollup/plugin-typescript: You are using one of Typescript's compiler options 'declaration', 'declarationMap' or 'composite'. In this case 'outDir' or 'declarationDir' must be specified to generate declaration files.
>...
>    at validatePaths (/home/josh/.../node_modules/@rollup/plugin-typescript/dist/cjs/index.js:423:21)

I am running:
```shell
rollup -c rollup-lambdas.config.ts --configPlugin typescript
```

It appears that the plugin is using my `tsconfig.json` instead of `tsconfig-lambdas.json`. I added logging to `@rollup/plugin-typescript/dist/cjs/index.js:423` (`console.log(compilerOptions)`) and I get this output:

```shell
{
  // ...
  configFilePath: '/home/josh/.../tsconfig.json',
}
```

To get around this I renamed the original `tsconfig.json` to `tsconfig-main.json` and `tsconfig-lambdas.json` to `tsconfig.json`, now the plugin uses the "correct" (default) tsconfig and my build works.

How can I tell the plugin to use my other `tsconfig`?

### Your Proposal for Changes

Not sure.

**Comment by lukastaegert** [comment]
From the docs https://rollupjs.org/command-line-interface/#configplugin-plugin:

> This option supports the same syntax as the [--plugin](https://rollupjs.org/#p-plugin-plugin-plugin) option i.e., you can specify the option multiple times, you can omit the @rollup/plugin- prefix and just write typescript and you can specify plugin options via `={...}`.

This last part is how you can specify such options while the options for the TypeScript plugin can be found here https://github.com/rollup/plugins/blob/master/packages/typescript/README.md#tsconfig

**Comment by JoshMcCullough** [comment]
I saw that and I did try this (sorry, should have specified in the OP):
```shell
rollup -c rollup-lambdas.config.ts --configPlugin typescript={tsconfig:tsconfig-lambdas.json} --bundleConfigAsCjs
rollup -c rollup-lambdas.config.ts --configPlugin typescript={tsconfig:'tsconfig-lambdas.json'} --bundleConfigAsCjs
rollup -c rollup-lambdas.config.ts --configPlugin typescript={tsconfig:"tsconfig-lambdas.json"} --bundleConfigAsCjs
```

All of the above result in:
>[!] ReferenceError: tsconfig is not defined
    at eval (eval at loadAndRegisterPlugin (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/shared/loadConfigFile.js:366:30), <anonymous>:3:18)
    at loadAndRegisterPlugin (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/shared/loadConfigFile.js:366:64)
    at addPluginsFromCommandOption (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/shared/loadConfigFile.js:341:23)
    at loadTranspiledConfigFile (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/shared/loadConfigFile.js:499:5)
    at getConfigFileExport (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/shared/loadConfigFile.js:449:20)
    at Object.loadConfigFile (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/shared/loadConfigFile.js:430:59)
    at getConfigs (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/bin/rollup:1728:39)
    at runRollup (/home/josh/Projects/teslagov/clarakm-mono-repo/ts/node_modules/rollup/dist/bin/rollup:1699:43)

**Comment by danielvy** [comment]
I find that using Typescript Rollup config files can be challenging and frustrating if you need to use different Typescript config options for your main source code. 

By the way, Rollup doesn't follow standard Typescript behavior when resolving `tsconfig.json` files like it should, so you can't put your Rollup config ts file in subdirectory and put a different `tsconfig.json` there like one would expect. It also seems that `@rollup/plugin-typescript` plugin reuses the last loaded `tsconfig.json`.


With that, the way I was able to make it work is:

Create basic `tsconfig.rollup.json` just for Rollup config script.

Use `rollup -c rollup.config.ts --configPlugin typescript={tsconfig:'tsconfig.rollup.json'}` to run Rollup.

In your `rollup.config.ts`, explicitly specify the `tsconfig.json` for your code:
```typescript
import rollupTypescript from "@rollup/plugin-typescript";
import type { RollupOptions } from "rollup";


const config: RollupOptions = {	
	...
	
	plugins: [		
		rollupTypescript({
			// Source tsconfig
			tsconfig: "tsconfig.json"
		}),
	],
}
export default config;
```

I hope this will be addressed sometime to make using Typescript config in Rollup less cumbersome or at least documented more clearly.

**Comment by JoshMcCullough** [comment]
Thanks, I'll give it a try.

**Comment by joyt** [comment]
For anyone else who was struggling with the workaround in https://github.com/rollup/plugins/issues/1713#issuecomment-2096028981, I needed to escape the quotes (it looks like the yargsparser used by rollup strips quotations marks):

`rollup -c rollup.config.ts --configPlugin typescript={tsconfig:\'tsconfig.rollup.json\'}`

**Comment by ThePlenkov** [comment]
@joyt I would never ever guess that I should try this - but it worked!  Thanks! I'm curious now if there will be a simpler solution. Ideally tsconfig,json at least should be picked up from a folder with rollup.config.ts

**Comment by goddnsgit** [comment]
> 大家好。这个问题已经 60 天没有得到任何反馈，所以我们将关闭它进行日常维护。如果这个问题仍然存在，请考虑提交一个 Pull 请求来解决它。即使问题已经关闭，我们也欢迎进一步讨论。如果评论区有任何可操作的内容，我们会考虑重新开启它 [。ⓘ](https://github.com/probot/stale#is-closing-stale-issues-really-a-good-idea)

这是逃避问题
