### ISSUE TITLE
@rollup/plugin-commonjs  works the unexpected with ant-design-vue

### ISSUE THREAD

**Issue by chaoXO** [rollup/plugins#1760]
- Rollup Plugin Name: 
- Rollup Plugin Version:
- Rollup Version:
- Operating System (or Browser):
- Node Version:
- Link to reproduction _(⚠️ read below)_:

**Comment by chaoXO** [comment]
Rollup Plugin Name:
commonjs

Rollup Plugin Version:
26.0.1

Rollup Version:
2.77.3

Operating System (or Browser):
chrome

Node Version:
v20.17.0

Link to reproduction (⚠️ read below):
https://stackblitz.com/edit/rollup-repro-f122t7?file=package.json

Expected Behavior
the build thing can be load correctly

Actual Behavior
Uncaught TypeError: require$$1$Z.concat is not a function
    at require_objectGopn (index.30a139b1.js:6772:33)
    at index.30a139b1.js:6779:14


Additional Information
may concern with ' 'hiddenKeys = require('./_enum-bug-keys').concat('length', 'prototype')'' from "ant-design-vue": "^1.7.8"



Actual Behavior
Additional Information
