### ISSUE TITLE
`@rollup/plugin-typescript` fileName or name properties of emitted chunks

### ISSUE THREAD

**Issue by paulober** [rollup/plugins#1814]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: 12.1.1
- Rollup Version: 4.27.2
- Operating System (or Browser): macOS
- Node Version: 20.16.0
- Link to reproduction _(⚠️ read below)_:

### Expected Behavior

Compile like before update to v12+

### Actual Behavior

I receive following error if `declaration` in the tsconfig compiler options is set to `true`:

```console
src/tests/index.ts → dist/tests/index.cjs...
[!] (plugin typescript) RollupError: The "fileName" or "name" properties of emitted chunks and assets must be strings that are neither absolute nor relative paths, received "../command.d.ts".
    at getRollupError (/Users/paulober/Developer/pico-mpy-com/node_modules/.pnpm/rollup@4.27.2/node_modules/rollup/dist/shared/parseAst.js:285:41)
    at Object.error (/Users/paulober/Developer/pico-mpy-com/node_modules/.pnpm/rollup@4.27.2/node_modules/rollup/dist/shared/parseAst.js:281:42)
    at FileEmitter.emitFile (/Users/paulober/Developer/pico-mpy-com/node_modules/.pnpm/rollup@4.27.2/node_modules/rollup/dist/shared/rollup.js:291:36)
    at file:///Users/paulober/Developer/pico-mpy-com/node_modules/.pnpm/@rollup+plugin-typescript@12.1.1_rollup@4.27.2_tslib@2.8.1_typescript@5.6.3/node_modules/@rollup/plugin-typescript/dist/es/index.js:888:22
    at Array.forEach (<anonymous>)
    at Object.generateBundle (file:///Users/paulober/Developer/pico-mpy-com/node_modules/.pnpm/@rollup+plugin-typescript@12.1.1_rollup@4.27.2_tslib@2.8.1_typescript@5.6.3/node_modules/@rollup/plugin-typescript/dist/es/index.js:873:46)
    at /Users/paulober/Developer/pico-mpy-com/node_modules/.pnpm/rollup@4.27.2/node_modules/rollup/dist/shared/rollup.js:1087:40
```

**Comment by paulober** [comment]
I case you decide to look at this: It can be solved by setting the `declarationsDir` option. See following [commit](https://github.com/paulober/pico-mpy-com/commit/7c53ea4a83ff0fea04058e41d52f569bcfe87787) for my workaround.
