### ISSUE TITLE
node-resolve 7.1.0 breaks import of submodule of tierce party

### ISSUE THREAD

**Issue by rhanka** [rollup/plugins#193]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 7.1.0
- Rollup Version: 1.31
- Operating System (or Browser): Ubuntu 18.04
- Node Version: 13.7.0

### How Do We Reproduce?

import icon of a @fortawesome library :

```
import { faLightbulb } from '@fortawesome/free-regular-svg-icons';
```

using following rollup.config.js

```
import svelte from 'rollup-plugin-svelte';
import replace from '@rollup/plugin-replace';
import resolve from '@rollup/plugin-node-resolve';
import commonjs from '@rollup/plugin-commonjs';
import livereload from 'rollup-plugin-livereload';
import { terser } from 'rollup-plugin-terser';

const production = !process.env.ROLLUP_WATCH;

export default {
	input: 'src/main.js',
	output: {
		sourcemap: true,
		format: 'iife',
		name: 'app',
		file: 'public/build/bundle.js'
	},
	plugins: [
		svelte({
			// enable run-time checks when not in production
			dev: !production,
			// we'll extract any component CSS out into
			// a separate file — better for performance
			css: css => {
				css.write('public/build/bundle.css');
			}
		}),
		replace({
			// you're right, you shouldn't be injecting this
			// into a client script :)
			__ES_PROXY_PATH__: process.env.ES_PROXY_PATH,
			__APP__: process.env.APP,
			__APP_VERSION__: process.env.APP_VERSION
		  }),
		// If you have external dependencies installed from
		// npm, you'll most likely need these plugins. In
		// some cases you'll need additional configuration —
		// consult the documentation for details:
		// https://github.com/rollup/plugins/tree/master/packages/commonjs
		resolve({
			browser: true,
			dedupe: importee => importee === 'svelte' || importee.startsWith('svelte/')
		}),
		commonjs(),

		// In dev mode, call `npm run start` once
		// the bundle has been generated
		!production && serve(),

		// Watch the `public` directory and refresh the
		// browser on changes when not in production
		!production && livereload('public'),

		// If we're building for production (npm run build
		// instead of npm run dev), minify
		production && terser()
	],
	watch: {
		clearScreen: false
	}
};

function serve() {
	let started = false;

	return {
		writeBundle() {
			if (!started) {
				started = true;

				require('child_process').spawn('npm', ['run', 'start', '--', '--dev'], {
					stdio: ['ignore', 'inherit', 'inherit'],
					shell: true
				});
			}
		}
	};
}
```

### Expected Behavior

should import faLightbulb as declared in @fortawesome/free-regular-svg-icons/index.js
like in 7.0.0
both in dev and production mode

### Actual Behavior
Returns following error:
```
Error: 'faLightbulb' is not exported by node_modules/@fortawesome/free-regular-svg-icons/index.js
    at error (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at handleMissingExport (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:9721:28)
    at Module.traceVariable (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:10159:24)
    at ModuleScope.findVariable (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:8766:39)
    at FunctionScope.findVariable (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at ChildScope.findVariable (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:3065:38)
    at Identifier$1.bind (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at Property$1.bind (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at Property$1.bind (/deces-ui/node_modules/rollup/dist/shared/node-entry.js:8388:15)
```

**Comment by shellscape** [comment]
Please share a proper reproduction as per the issue template or we'll have to close this one without triage.

**Comment by rhanka** [comment]
Is the format no okay or do you have a problem with reproducting the issue ?

**Comment by shellscape** [comment]
It's pretty clear in the issue template what we are asking for:

>  Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

I'm also unsure what "tierce" is. We won't triage your issue until you provide a proper reproduction.

**Comment by rhanka** [comment]
Ok sorry for that. You I close it till I make the update (tonight)
