### ISSUE TITLE
node-resolve v7.1.0 regression - looks like it's trying to use a CommonJS file when it should be using an ES module file?

### ISSUE THREAD

**Issue by dumbmatter** [rollup/plugins#195]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 7.1.0
- Rollup Version: 1.31.0
- Operating System (or Browser): Ubuntu 19.10
- Node Version: 13.7.0

### How Do We Reproduce?

https://github.com/dumbmatter/rollup-plugin-node-resolve-7.1.0

Clone the repo, `npm install`, `npm run build`.

### Expected Behavior

The command should complete with no errors.

### Actual Behavior

I see this error:

```
$ npm run build

> @ build /home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0
> rollup -c


index.js → bundle.js...
[!] Error: 'openDB' is not exported by node_modules/idb/build/cjs/index.js
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
index.js (1:9)
1: import { openDB } from 'idb';
            ^
2: console.log(openDB);
Error: 'openDB' is not exported by node_modules/idb/build/cjs/index.js
    at error (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at handleMissingExport (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:9721:28)
    at Module.traceVariable (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:10159:24)
    at ModuleScope.findVariable (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:8766:39)
    at Identifier$1.bind (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:4403:40)
    at CallExpression$1.bind (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:3148:31)
    at CallExpression$1.bind (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:6718:15)
    at ExpressionStatement$1.bind (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:3152:23)
    at Program$1.bind (/home/jdscheff/projects/rollup-plugin-node-resolve-7.1.0/node_modules/rollup/dist/shared/node-entry.js:3148:31)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `rollup -c`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jdscheff/.npm/_logs/2020-02-03T06_32_47_021Z-debug.log
```

If I downgrade to v7.0.0 with `npm install @rollup/plugin-node-resolve@7.0.0` then the command works.

I haven't looked into the internals of this plugin at all, but from the error message, it seems strange that it's trying to import the CommonJS file rather than the ES modules file, which [is available](https://github.com/jakearchibald/idb/blob/master/package.json#L5-L6).

I also observed this same problem happening with other packages when I tried upgrading a larger project to v7.1.0.

---

I hope I filled out all the information you need, let me know if you need anything else. And thank you for all your work on rollup, I'm a big fan!

**Comment by TrySound** [comment]
I fixed this by adding `mainFields: ['browser', 'module', 'main]` instead of `browser: true` in my project.

**Comment by Robinfr** [comment]
Same happens when using the Mobx library.

**Comment by vanruesc** [comment]
Can confirm that the behaviour changed from `7.0.0` to `7.1.0`.

The documentation says that the default [mainFields](https://github.com/rollup/plugins/tree/master/packages/node-resolve#mainfields) are `['module', 'main']`, but the code says otherwise: https://github.com/rollup/plugins/blob/master/packages/node-resolve/src/util.js#L36

**Comment by TrySound** [comment]
Ah, right. The order is confused.
