### ISSUE TITLE
Unexpected token `function` in node module

### ISSUE THREAD

**Issue by zgagnon** [rollup/plugins#227]
- Rollup Plugin Name: @rollup/plugin-commonjs
- Rollup Plugin Version: 11.0.2
- Rollup Version: 1.31.1
- Operating System (or Browser): MacOS
- Node Version: v12.13.0

### How Do We Reproduce?

Minimal repository link: https://github.com/zgagnon/rollup-depedency-bug-reproduce

run `yarn; yarn rollup`

### Expected Behavior

A file called `bundle.js` is produced. It bundles the `aws-xray-sdx-core` and all dependencies.

### Actual Behavior

```
[!] Error: Unexpected token
node_modules/continuation-local-storage/context.js (17:0)
15: if (!process.addAsyncListener) require('async-listener');
16:
17: function Namespace(name) {
    ^
18:   this.name   = name;
19:   // changed in 2.7: no default context
Error: Unexpected token
    at error (/Users/zgagnon/git/bundle_test/node_modules/rollup/dist/shared/node-entry.js:5400:30)
    at Module.error (/Users/zgagnon/git/bundle_test/node_modules/rollup/dist/shared/node-entry.js:9820:16)
    at tryParse (/Users/zgagnon/git/bundle_test/node_modules/rollup/dist/shared/node-entry.js:9713:23)
    at Module.setSource (/Users/zgagnon/git/bundle_test/node_modules/rollup/dist/shared/node-entry.js:10076:33)
    at /Users/zgagnon/git/bundle_test/node_modules/rollup/dist/shared/node-entry.js:12362:20
    at async Promise.all (index 0)
```

**Comment by shellscape** [comment]
Hey folks. This issue hasn't received any traction for more than 90 days, so we're going to close this for housekeeping. If this is still an ongoing issue, please do consider contributing a Pull Request to resolve it. Further discussion is always welcome even with the issue closed. If anything actionable is posted in the comments, we'll consider reopening it.

**Comment by hanvyj** [comment]
Also seen this issue:

```
[!] Error: Unexpected token
node_modules\continuation-local-storage\context.js (17:0)
15: if (!process.addAsyncListener) require('async-listener');
16:
17: function Namespace(name) {
    ^
18:   this.name   = name;
19:   // changed in 2.7: no default context
Error: Unexpected token
    at error (C:\projects\socos-database-client\node_modules\rollup\dist\shared\rollup.js:5171:30)
    at Module.error (C:\projects\socos-database-client\node_modules\rollup\dist\shared\rollup.js:9603:16)
    at tryParse (C:\projects\socos-database-client\node_modules\rollup\dist\shared\rollup.js:9517:23)
    at Module.setSource (C:\projects\socos-database-client\node_modules\rollup\dist\shared\rollup.js:9902:30)
    at ModuleLoader.addModuleSource (C:\projects\socos-database-client\node_modules\rollup\dist\shared\rollup.js:17777:20)
```
