### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by milobluebell** [rollup/plugins#245]
- Rollup Plugin Name: @rollup/plugin-typescript
- Rollup Plugin Version: ^3.0.0
- Rollup Version: ^1.32.0
- Operating System (or Browser): mac catalina
- Node Version: 10.16.3

### Expected Behavior
build my libaray correctly

### Actual Behavior
BUT, when:
```
rollup -c
```
is shown:
```
[!] (plugin typescript) TypeError: Cannot read property 'get' of undefined
TypeError: Cannot read property 'get' of undefined
    at getSymbol (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:35281:38)
    at getJsxLibraryManagedAttributes (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:55161:36)
    at getJsxManagedAttributesFromLocatedAttributes (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:54390:30)
    at getJsxPropsTypeFromCallSignature (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:54340:25)
    at getEffectiveFirstArgumentForJsxSignature (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:54335:19)
    at resolveJsxOpeningLikeElement (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:57537:112)
    at resolveSignature (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:57580:28)
    at getResolvedSignature (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:57602:26)
    at checkJsxOpeningLikeElementOrOpeningFragment (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:55325:27)
    at checkJsxElementDeferred (/Users/milobluebell/Documents/myfuns/node_modules/typescript/lib/typescript.js:54886:13)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by shellscape** [comment]
Thanks for opening an issue. Citing the issue template:

>   Issues without minimal reproductions will be closed! Please provide one by:
>   1. Using the REPL.it plugin reproduction template at https://repl.it/@rollup/rollup-plugin-repro
>   2. Provide a minimal repository link (Read https://git.io/fNzHA for instructions).
>      These may take more time to triage than the other options.
>   3. Using the REPL at https://rollupjs.org/repl/

Please add a reproduction and we'll be happy to triage further.

There are also newer versions of that plugin available.
