### ISSUE TITLE
@rollup/plugin-babel does not support async tranformations

### ISSUE THREAD

**Issue by perrin4869** [rollup/plugins#345]
- Rollup Plugin Name: `@rollup/plugin-babel`
- Rollup Plugin Version: `5.0.0`
- Rollup Version: `2.7.3`
- Operating System (or Browser): `slackware64-current`
- Node Version: `14.0`

### How Do We Reproduce?

https://github.com/perrin4869/rollup-babel-esm

After cloning:

```bash
npm ci
npx rollup -c rollup.config.js
```

Tested with `node@14`

### Expected Behavior
Should output `./commonjs/entry.cjs`

### Actual Behavior
Fails with error:

```
src/index.js → commonjs/entry.cjs...
[!] (plugin babel) Error: /home/perrin4869/projects/nodejs/rollup-babel-esm/.babelrc.js: Error while loading config - You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.
src/index.js
Error: /home/perrin4869/projects/nodejs/rollup-babel-esm/.babelrc.js: Error while loading config - You appear to be using a native ECMAScript module configuration file, which is only supported when running Babel asynchronously.
    at loadCjsOrMjsDefault (/home/perrin4869/projects/nodejs/rollup-babel-esm/node_modules/@babel/core/lib/config/files/module-types.js:59:13)
    at loadCjsOrMjsDefault.next (<anonymous>)
    at readConfigJS (/home/perrin4869/projects/nodejs/rollup-babel-esm/node_modules/@babel/core/lib/config/files/configuration.js:190:47)
    at readConfigJS.next (<anonymous>)
    at Function.<anonymous> (/home/perrin4869/projects/nodejs/rollup-babel-esm/node_modules/@babel/core/lib/gensync-utils/async.js:26:3)
    at Generator.next (<anonymous>)
    at evaluateSync (/home/perrin4869/projects/nodejs/rollup-babel-esm/node_modules/gensync/index.js:244:28)
    at Function.sync (/home/perrin4869/projects/nodejs/rollup-babel-esm/node_modules/gensync/index.js:84:14)
    at sync (/home/perrin4869/projects/nodejs/rollup-babel-esm/node_modules/@babel/core/lib/gensync-utils/async.js:66:25)
    at sync (/home/perrin4869/projects/nodejs/rollup-babel-esm/node_modules/gensync/index.js:177:19)
```

As mentioned in my previous issue, I expect this to be the case because the [`babel` documentation mentioned](https://babeljs.io/blog/2020/01/11/7.8.0#support-every-configuration-file-extension-10783-https-githubcom-babel-babel-pull-10783-and-10903-https-githubcom-babel-babel-pull-10903) that the next version of `@rollup/plugin-babel` would support async Babel transformations, but it does not seem to be the case.

**Comment by shellscape** [comment]
Thanks for the issue. 

/cc @Andarist

**Comment by Andarist** [comment]
Thanks for the repro case - gonna handle this 🔜
