### ISSUE TITLE
[typescript] `export * from "./myModule.js"` Error TS2305: Module "..." has no exported  member '...' - for JS but not for TS.

### ISSUE THREAD

**Issue by htho** [rollup/plugins#373]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 4.1.1
- Rollup Version: 2.8.2
- tslib Version: 1.11.2
- typescript Version: 3.8.3
- Operating System (or Browser): Windows 10
- Node Version: 12.10.0

### How Do We Reproduce?

This is the offending code:

```typescript
export * from "./answersFromJsToBeReexported";
```

Interestingly it works with modules exported from TypeScript files, but not from JavaScript files.

I created a repro at https://github.com/htho/repro--rollup-plugin-typescript--export-asterisk-from-js

### Expected Behavior

It should run without errors.

### Actual Behavior

```
PS C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js> npx rollup -c

./src/dummy.ts → dist...
[!] (plugin typescript) Error: @rollup/plugin-typescript TS2305: Module '"../../../../../Dev/github.com/htho/repro--rollup-plugin-typescript--export-asterisk-from-js/src/reexports"' has no exported member 'halfTheAnswer'.
src\dummy.ts (3:2)

3  halfTheAnswer,
   ~~~~~~~~~~~~~

Error: @rollup/plugin-typescript TS2305: Module '"../../../../../Dev/github.com/htho/repro--rollup-plugin-typescript--export-asterisk-from-js/src/reexports"' has no exported member 'halfTheAnswer'.
    at error (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\rollup\dist\shared\rollup.js:161:30)
    at throwPluginError (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\rollup\dist\shared\rollup.js:16925:12)
    at Object.error (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\rollup\dist\shared\rollup.js:17944:24)
    at emitDiagnostic (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\@rollup\plugin-typescript\dist\index.js:415:17)
    at reportDiagnostics (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\@rollup\plugin-typescript\dist\index.js:423:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\typescript\lib\typescript.js:102879:21)
    at Object.result.afterProgramCreate (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\typescript\lib\typescript.js:103054:13)
    at Object.afterProgramCreate (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\@rollup\plugin-typescript\dist\index.js:444:29)
    at synchronizeProgram (C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js\node_modules\typescript\lib\typescript.js:103300:22)

PS C:\Dev\github.com\htho\repro--rollup-plugin-typescript--export-asterisk-from-js>
```

**Comment by shellscape** [comment]
We're closing this issue as stale as it's more than 30 days without activity, and without an associated Pull Request. Please feel free to continue discussion. We'll reopen this issue if anything actionable is posted.
