### ISSUE TITLE
TypeScript build changes when using a tsconfig which no-op extends another tsconfig

### ISSUE THREAD

**Issue by dgp1130** [rollup/plugins#429]
- Rollup Plugin Name: `@rollup/plugin-typescript`
- Rollup Plugin Version: 4.1.2
- Rollup Version: 2.11.2
- Operating System (or Browser): Ubuntu Linux 20.04
- Node Version: v14.3.0

### How Do We Reproduce?

Minimal reproduction is at https://github.com/dgp1130/rollup-typescript-tsconfig-bug, more complete instructions are in the README.

As a TL;DR:

Importing CommonJS code with adjacent TypeScript definitions fails when using a `tsconfig.json` which extends another `tsconfig.json` (even with no behavior changes from extending). Essentially the build succeeds when using `tsconfig.json`, but fails when using `tsconfig.app.json`, even when that config is merely:

```json
// tsconfig.app.json
{
  "extends": "./tsconfig.json"
  // **No** additional changes to the configuration.
}
```

### Expected Behavior

I would expect the build to be unchanged between using `tsconfig.json` or using a `tsconfig.app.json` which only extends `tsconfig.json`.

### Actual Behavior

The build breaks by failing to import the CommonJS file with the error:

```
src/foo.ts → dist/foo.js...
[!] Error: 'bar' is not exported by src/bar.js, imported by src/foo.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/foo.ts (2:9)
1: // Fails to import.
2: import { bar } from './bar';
            ^
3: bar();
4: //# sourceMappingURL=foo.js.map
Error: 'bar' is not exported by src/bar.js, imported by src/foo.ts
    at error (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:217:30)
    at Module.error (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:15145:16)
    at handleMissingExport (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:15042:28)
    at Module.traceVariable (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:15520:24)
    at ModuleScope.findVariable (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:14199:39)
    at Identifier$1.bind (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:10080:40)
    at CallExpression$1.bind (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:9707:23)
    at CallExpression$1.bind (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:12164:15)
    at ExpressionStatement$1.bind (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:9707:23)
    at Program$1.bind (/home/dparker/Source/rollup-tsconfig/node_modules/rollup/dist/shared/rollup.js:9703:31)
```

Changing file names has no impact on the result of the build. It only fails if I use the `extends` feature of `tsconfig.json`.

**Comment by dgp1130** [comment]
I should also point out that running `tsc` directly with the same `tsconfig` files successfully compile. In the same repository:

```
dparker@gryphon (~/Source/rollup-tsconfig)
[20-05-31 20:02:05]$ git checkout master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
dparker@gryphon (~/Source/rollup-tsconfig)
[20-05-31 20:02:12]$ npx typescript -p tsconfig.json
npx: installed 1 in 1.489s
dparker@gryphon (~/Source/rollup-tsconfig)
[20-05-31 20:02:18]$ npx typescript -p tsconfig.app.json
npx: installed 1 in 1.363s
dparker@gryphon (~/Source/rollup-tsconfig)
[20-05-31 20:02:22]$ git checkout broken
Switched to branch 'broken'
Your branch is up to date with 'origin/broken'.
dparker@gryphon (~/Source/rollup-tsconfig)
[20-05-31 20:04:35]$ npx typescript -p tsconfig.json
npx: installed 1 in 1.332s
dparker@gryphon (~/Source/rollup-tsconfig)
[20-05-31 20:04:40]$ npx typescript -p tsconfig.app.json
npx: installed 1 in 1.33s
```

This leads me to believe the problem is in the rollup plugin.
