### ISSUE TITLE
No valid exports main found for pluginutils

### ISSUE THREAD

**Issue by NetOperatorWibby** [rollup/plugins#473]
- Rollup Plugin Name: `@rollup/pluginutils`
- Rollup Plugin Version: The latest (all scoped plugins seem to use `pluginutils`)
- Rollup Version: `2.18.0`
- Operating System (or Browser): macOS Catalina/macOS Big Sur
- Node Version: `13.5.0`

### How Do We Reproduce?

Have a Rollup project use TypeScript and include the plugins I listed at the bottom of this intro.

### Expected Behavior

I expect to continue working on my project without issue.

### Actual Behavior

```error
[!] Error: No valid exports main found for '~/project/node_modules/@rollup/pluginutils'
Error: No valid exports main found for '~/project/node_modules/@rollup/pluginutils'
    at resolveExportsTarget (internal/modules/cjs/loader.js:622:9)
    at applyExports (internal/modules/cjs/loader.js:499:14)
    at resolveExports (internal/modules/cjs/loader.js:548:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:654:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (~/project/node_modules/@rollup/plugin-commonjs/dist/index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
```

The plugins in my rollup config are `@rollup/plugin-commonjs`, `rollup-plugin-livereload`, `@rollup/plugin-node-resolve`, `rollup-plugin-stimulus`, and `@rollup/plugin-sucrase`.

When I uninstall all the `@rollup` scoped plugins, the issue disappears. However, as I'm using TypeScript I need Sucrase to transpile.

This is **not** a macOS beta issue because this was happening two days ago and I only upgraded my OS yesterday. All plugins listed are using the latest versions.

**Comment by TrySound** [comment]
Hi, node 13.5 is very old node version which does not have proper es modules support. Please upgrade to stable LTS version (10, 12, 14).

**Comment by NetOperatorWibby** [comment]
Oh damn I’m using old mode?! Good grief.
