### ISSUE TITLE
[typescript] Cannot compile JS to target ES version

### ISSUE THREAD

**Issue by uasi** [rollup/plugins#474]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 5.0.0
- Rollup Version: 2.18.0
- Operating System (or Browser): macOS 10.15.4
- Node Version: 12.10.0

### How Do We Reproduce?

https://repl.it/@uasi/20200624-rollup-plugin-typescript-allowjs#rollup.config.js

```js
// input.ts
import './a.js';
import './b';

// a.js
{
  const { x, ...rest } = { x: 1, y: 2, z: 3 };
  console.log(`a.js: ${rest}`);
}

// b.ts
{
  const { x, ...rest } = { x: 1, y: 2, z: 3 };
  console.log(`b.ts: ${rest}`);
}

// rollup.config.js
const typescript = require('@rollup/plugin-typescript');
module.exports = {
  input: 'input.ts',
  plugins: [
    typescript({
      allowJs: true, // OR false
      target: 'ES5',
    })],
};
```

### Expected Behavior

Output is ES5:

```js
{
    var _a = { x: 1, y: 2, z: 3 }, x = _a.x, rest = __rest(_a, ["x"]);
    console.log("a.js: " + rest);
}

{
    var _a = { x: 1, y: 2, z: 3 }, x = _a.x, rest = __rest(_a, ["x"]);
    console.log("b.ts: " + rest);
}
```

### Actual Behavior

If `allowJs` is set to true:

```
[!] (plugin typescript) Error: @rollup/plugin-typescript TS5055: Cannot write file '/home/runner/20200624-rollup-plugin-typescript-allowjs/a.js' because it would overwrite input file.
Error: @rollup/plugin-typescript TS5055: Cannot write file '/home/runner/20200624-rollup-plugin-typescript-allowjs/a.js' because it would overwrite input file.
    at error (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/rollup/dist/shared/rollup.js:5154:30)
    at throwPluginError (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/rollup/dist/shared/rollup.js:17381:12)
    at Object.error (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/rollup/dist/shared/rollup.js:18002:24)
    at emitDiagnostic (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/@rollup/plugin-typescript/dist/index.js:415:17)
    at reportDiagnostics (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/@rollup/plugin-typescript/dist/index.js:423:9)
    at Array.forEach (<anonymous>)
    at emitFilesAndReportErrors (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/typescript/lib/typescript.js:105304:21)
    at Object.result.afterProgramCreate (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/typescript/lib/typescript.js:105474:13)
    at Object.afterProgramCreate (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/@rollup/plugin-typescript/dist/index.js:515:29)
    at synchronizeProgram (/home/runner/20200624-rollup-plugin-typescript-allowjs/node_modules/typescript/lib/typescript.js:105738:22)
```

Otherwise, the typescript plugin doesn't compile a.js and instead emit it unmodified:

```js
{
  const { x, ...rest } = { x: 1, y: 2, z: 3 };
  console.log(`a.js: ${rest}`);
}

{
    var _a = { x: 1, y: 2, z: 3 }, x = _a.x, rest = __rest(_a, ["x"]);
    console.log("b.ts: " + rest);
}
```

I know I could use the babel plugin along with the typescript plugin, but it would be better to just use one plugin to do the job.

**Comment by uasi** [comment]
I found that the output path check can be suppressed by, obviously, the `suppressOutputPathCheck` internal compiler option.

https://github.com/microsoft/TypeScript/blob/c388222b29228a572b4e3c9ca907863d0b1945c6/src/compiler/program.ts#L3200-L3209

So I gave it a try...

```patch
diff --git a/node_modules/@rollup/plugin-typescript/dist/index.js b/node_modules/@rollup/plugin-typescript/dist/index.js
index 2e28a32..11f0ed4 100644
--- a/node_modules/@rollup/plugin-typescript/dist/index.js
+++ b/node_modules/@rollup/plugin-typescript/dist/index.js
@@ -529,6 +529,7 @@ function typescript(options = {}) {
     const watchProgramHelper = new WatchProgramHelper();
     const parsedOptions = parseTypescriptConfig(ts, tsconfig, compilerOptions);
     parsedOptions.fileNames = parsedOptions.fileNames.filter(filter);
+    parsedOptions.options.suppressOutputPathCheck = true;
     const formatHost = createFormattingHost(ts, parsedOptions.options);
     const resolveModule = createModuleResolver(ts, formatHost);
     let program = null;
```

```patch
diff --git a/rollup.config.js b/rollup.config.js
index 34d43e6..c3d6ef6 100644
--- a/rollup.config.js
+++ b/rollup.config.js
@@ -5,5 +5,6 @@ module.exports = {
     typescript({
       allowJs: true,
       target: 'ES5',
+      include: ['*.[jt]s'],
     })],
 };
```

Seems like it's working.

```
$ npx rollup -c

input.ts → stdout...
{
    var _a = { x: 1, y: 2, z: 3 }, x = _a.x, rest = __rest(_a, ["x"]);
    console.log("a.js: " + rest);
}

{
    var _a$1 = { x: 1, y: 2, z: 3 }, x$1 = _a$1.x, rest$1 = __rest(_a$1, ["x"]);
    console.log("b.ts: " + rest$1);
}
```

**Comment by shellscape** [comment]
Thanks for following up with a workaround. We'll close this as resolved.
