### ISSUE TITLE
Plugin node-resolve for TypeScript doesn't work for importing "./file.js" when file is "file.ts"

### ISSUE THREAD

**Issue by heyheyhello** [rollup/plugins#479]
- Rollup Plugin Name: node-resolve
- Rollup Plugin Version: 8.1.0
- Rollup Version: 2.18.1
- Operating System (or Browser): Linux
- Node Version: 14.2.0

### How Do We Reproduce?

Use `import ... from './file.js'` when referring to a TS file called `file.ts`

https://repl.it/repls/DescriptiveDesertedLanservers

### Expected Behavior

If you're not familiar with TS then you may expect this to be expected behaviour, and that totally makes sense, but TS _does_ support importing other `.ts` files via `.js` extension. In fact, trying to write `.ts` yields: `An import path cannot end with a '.ts' extension. Consider importing './file' instead.ts(2691)`.

Writing `import ... from './file'` (no extension) works, but to quote Rich Harris from #14:

> Extension-less imports is a bad habit encouraged by Node's ill-conceived module resolution algorithm. Being explicit and obvious (rather than relying on scattered bits of magic) makes life easier for whichever developer inherits a project

I think supporting `.js` is the right option. The plugin could handle TS imports with the `.js` extension when given `{ extensions: ['.js', '.ts'] }` to clarify that TS imports should be supported.

### Actual Behavior

Import _must_ be `./file` (ambiguous) or `./file.ts` (not allowed by TS but does work). Importing `.js` yields:

```
[!] Error: Could not resolve './file.js' from sinuous-trace/log/index.ts
Error: Could not resolve './file.js' from sinuous-trace/log/index.ts
    at error (/home/today/_/work/sinuous-packages/node_modules/rollup/dist/shared/rollup.js:5154:30)
    at ModuleLoader.handleResolveId (/home/today/_/work/sinuous-packages/node_modules/rollup/dist/shared/rollup.js:17837:24)
    ...
```

Which, I understand _is kinda expected_ because './file.js' literally doesn't exist so...yeah it's tricky.

**Comment by heyheyhello** [comment]
![image](https://user-images.githubusercontent.com/44614862/86153531-b0b9c400-bab6-11ea-8d23-fcbafcb983d4.png)
![image](https://user-images.githubusercontent.com/44614862/86153959-42c1cc80-bab7-11ea-9448-b8ed43d195bb.png)
![image](https://user-images.githubusercontent.com/44614862/86154016-5a995080-bab7-11ea-9641-fd0eff48faa3.png)

Also thought I'd mention that `@rollup/plugin-typescript` works out of the box for this since it uses TypeScript's resolver
