### ISSUE TITLE
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received 

### ISSUE THREAD

**Issue by mjmnagy** [rollup/plugins#563]
- Rollup Plugin Name: CommonJs
- Rollup Plugin Version: 15.0.0
- Rollup Version: 2.26.9
- Operating System (or Browser): MS 10 / chrome / firefox
- Node Version: 12.18.3
- Link to reproduction _(⚠️ read below)_: https://github.com/mjmnagy/rollup-error-Sept-01-2020

### Expected Behavior
- Import file using dynamic import

### Actual Behavior
```
internal/fs/utils.js:453
    throw err;
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'path' must be a string or Uint8Array without null bytes. Received 'B:\\icons\\node_modules\\\u0000commonjs-dynamic-register:\\icons\\brands\\500px.js\\package.json'
    at readFile (fs.js:297:3)
    at go$readFile (B:\icons\node_modules\graceful-fs\graceful-fs.js:118:14)
    at Object.readFile (B:\icons\node_modules\graceful-fs\graceful-fs.js:115:12)
    at Storage.provide (B:\icons\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:90:3)
    at CachedInputFileSystem.readFile (B:\icons\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:269:25)
    at CachedInputFileSystem._readJson (B:\icons\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:223:10)
    at Storage.provide (B:\icons\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:90:3)
    at CachedInputFileSystem.readJson (B:\icons\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:273:25)
    at forEachBail (B:\icons\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:22:26)
    at forEachBail (B:\icons\node_modules\enhanced-resolve\lib\forEachBail.js:14:3)
    at findDescriptionFile (B:\icons\node_modules\enhanced-resolve\lib\DescriptionFileUtils.js:17:3)
    at resolver.getHook.tapAsync (B:\icons\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:24:27)
    at AsyncSeriesBailHook.eval [as callAsync] (eval at create (B:\icons\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Resolver.doResolve (B:\icons\node_modules\enhanced-resolve\lib\Resolver.js:282:16)
    at resolver.getHook.tapAsync (B:\icons\node_modules\enhanced-resolve\lib\JoinRequestPlugin.js:25:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @fsu/icons@0.0.38 dev: `nuxt`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @fsu/icons@0.0.38 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

### Additional Information
Attempted to use the REPL but was not successful
- Rollup completes without any problems

IM LOST

**Comment by TomCaserta** [comment]
@mjmnagy did you manage to find a solution to your issue? Also getting this from the commonjs plugin, checking what it's outputting is code like the following:

```
import '\u0000C:/Users/tomca/Documents/Projects/XXX/packages/XXX/file.js?commonjs-require';
```

But this is being output directly to the bundle, I suspect it's supposed to be picking up that import later on when it bundles everything together but I can't see why that's not happening. I am using cypress with rollup (via a so may be something to do with that preprocessor): https://github.com/lmarqs/cypress-rollup-preprocessor 

Taking a look at that code now. I suspect your problem may have been similar in nature?

**Comment by mjmnagy** [comment]
@TomCaserta i removed all lazy and dynamic imports and it worked
