### ISSUE TITLE
Can't resolve dependencies if virtual module is not in top level directory

### ISSUE THREAD

**Issue by Tundon** [rollup/plugins#566]
- Rollup Plugin Name: @rollup/plugin-virtual
- Rollup Plugin Version: ^2.0.3
- Rollup Version: ^2.26.10
- Operating System (or Browser): macOS
- Node Version: v12.18.3
- Link to reproduction _(⚠️ read below)_: https://repl.it/repls/OldfashionedAnnualCache#rollup.config.js

### Expected Behavior

The console should print the final build

### Actual Behavior

Error happened:
```
[!] Error: Could not resolve './lib' from virtual:src/virtual-entry.js
Error: Could not resolve './lib' from virtual:src/virtual-entry.js
    at error (/home/runner/OldfashionedAnnualCache/node_modules/rollup/dist/shared/rollup.js:5211:30)
    at ModuleLoader.handleResolveId (/home/runner/OldfashionedAnnualCache/node_modules/rollup/dist/shared/rollup.js:18246:24)
    at /home/runner/OldfashionedAnnualCache/node_modules/rollup/dist/shared/rollup.js:18238:22
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/home/runner/OldfashionedAnnualCache/node_modules/rollup/dist/shared/rollup.js:18236:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/runner/OldfashionedAnnualCache/node_modules/rollup/dist/shared/rollup.js:18213:9)
    at async Promise.all (index 0)
```

### Additional Information

There are two configs inside the `rollup.config.js`, the first one fails (the virtual module is in sub folder) while the second works (the virtual module is in top level)

**Comment by matthew-dean** [comment]
Getting the same (similar?) issue, where modules can't be resolved from virtual modules. Seems to have nothing to do with a top-level directory though.

**Comment by shellscape** [comment]
@matthew-dean the virtual plugin is from the very early days of Rollup, so I'd guess they cannot. I'd suggest a new issue with your use case as a bug (but really a hybrid bug/feature). Also encourage you to try and work on a fix, since we don't currently have an active maintainer for that plugin. (It hasn't historically needed much love)
