### ISSUE TITLE
UMD not working with typescript "Expected fileName to be present in command line"

### ISSUE THREAD

**Issue by jrgleason** [rollup/plugins#569]
- Rollup Plugin Name: plugin-typescript
- Rollup Plugin Version: latest
- Rollup Version: latest
- Operating System (or Browser): OSX
- Node Version: 15
- Link to reproduction https://github.com/jrgleason/rollup-ng-typescript-demo/tree/MJS_CALLING_TS

### Expected Behavior

I should be able to compile the UMD bundle the same way I can using mjs in the master branch

### Actual Behavior

```
[!] (plugin typescript) Error: Could not load .../rollup-ng-typescript-demo/ng/Application.ts: Debug Failure. False expression: Expected fileName to be present in command line
Error: Could not load .../rollup-ng-typescript-demo/ng/Application.ts: Debug Failure. False expression: Expected fileName to be present in command line
    at Object.getOutputFileNames (...rollup-ng-typescript-demo/node_modules/typescript/lib/typescript.js:97278:18)
    at findTypescriptOutput (...rollup-ng-typescript-demo/node_modules/@rollup/plugin-typescript/dist/index.js:391:33)
    at Object.load (...rollup-ng-typescript-demo/node_modules/@rollup/plugin-typescript/dist/index.js:592:28)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by jrgleason** [comment]
I have debuged into getOutputFiles and I see 

`commandLine.fileNames.filter(s=>s.includes("Application"))` returns an empty array

`inputFileName` looks correct

**Comment by jrgleason** [comment]
nm resolved it with adding this to the tsconfig.json...

    "include": [
      "node_modules",
      "ng" // needed this
    ]
