### ISSUE TITLE
resolveOnly error: "../module.js' is imported as an external by  ../module.js?commonjs-proxy, but is already an existing non-external module id"

### ISSUE THREAD

**Issue by NikolayMakhonin** [rollup/plugins#581]
- Rollup Plugin Name: @rollup/plugin-node-resolve and other (see below)
- Rollup Plugin Version: 9.0.0
- Rollup Version: 2.27.1
- Operating System (or Browser):
- Node Version: 12.17.0
- Link to reproduction _(⚠️ read below)_: https://github.com/NikolayMakhonin/rollup-plugin-node-resolve-bug

```json
  "dependencies": {
    "@babel/core": "7.11.6",
    "@babel/plugin-transform-runtime": "7.11.5",
    "@babel/runtime-corejs3": "7.11.2",
    "@rollup/plugin-babel": "5.2.1",
    "@rollup/plugin-commonjs": "15.0.0",
    "@rollup/plugin-node-resolve": "9.0.0",
    "rollup": "2.27.1"
  }
```

### Expected Behavior
I expect `npm run test` in [this repo](https://github.com/NikolayMakhonin/rollup-plugin-node-resolve-bug) without errors.
And the result (`bundle.js`) should not contains any `require(...)` calls, i.e. all modules should be resolved.
! The errors can be reproduced only with `resolveOnly` property

### Actual Behavior

For reproduce the errors use [this repo](https://github.com/NikolayMakhonin/rollup-plugin-node-resolve-bug) and run `npm run test` or `npm run test1`, `npm run test2`

#### test1:

module.js
```js
module.exports = {
    module: 0,
} 
```

app.js
```js
var obj = require('./module')
module.exports = obj
```

build.js
```js
const path = require('path')
const resolve = require('@rollup/plugin-node-resolve').default
const commonjs = require('@rollup/plugin-commonjs')
const {rollup} = require('rollup')

async function build() {
    const bundle = await rollup({
        input : require.resolve('./app.js'),
        plugins: [
            resolve({
                resolveOnly: [
                    /app|module/
                ],
                // dedupe(importee) {
                //    console.log(importee)
                //    return false
                // }
            }),
            commonjs(),
        ],
    })

    const result = await bundle.write({
        file: 'bundle.js',
        format: 'cjs'
    })

    console.log(result.output[0].code)
}

build()
    .catch(ex => console.error(ex))
```

Error for test1:
```js
Error: 'C:\projects\rollup-plugin-node-resolve-bug\test1\module.js' is imported as an external by  C:\projects\rollup-plugin-node-resolve-bug\test1\module.js?commonjs-proxy, but is already an existing non-external module id.
    at error (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:5211:30)
    at ModuleLoader.fetchResolvedDependency (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18239:24)
    at C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18248:102
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18248:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18225:9)
    at async Promise.all (index 1)
    at async ModuleLoader.fetchStaticDependencies (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18248:34)
    at async Promise.all (index 0) {
  code: 'INVALID_EXTERNAL_ID',
  watchFiles: [
    'C:\\projects\\rollup-plugin-node-resolve-bug\\test1\\app.js',
    '\u0000C:\\projects\\rollup-plugin-node-resolve-bug\\test1\\module.js?commonjs-proxy',
    'C:\\projects\\rollup-plugin-node-resolve-bug\\test1\\module.js'
  ]
}
```

#### test2

module.js
```js
console.log('qwe'.startsWith('q')) // babel insert runtime helpers here

module.exports = {
    module: 0,
}
```

app.js
```js
import obj from './module'
module.exports = obj
```

build.js
```js
const path = require('path')
const resolve = require('@rollup/plugin-node-resolve').default
const commonjs = require('@rollup/plugin-commonjs')
const {rollup} = require('rollup')
const {babel} = require('@rollup/plugin-babel')

async function build() {
    const bundle = await rollup({
        input : require.resolve('./app.js'),
        plugins: [
            resolve({
                resolveOnly: [
                    /babel|core-js/
                ],
                // dedupe(importee) {
                //     console.log(importee)
                //     return false
                // },
            }),
            commonjs(),
            babel({
                babelrc: false,
                exclude: 'node_modules/**',
                babelHelpers: 'runtime',
                plugins: [
                    [
                        '@babel/plugin-transform-runtime', {
                            corejs      : 3,
                            useESModules: true,
                        }
                    ],
                ],
            }),
        ],
    })

    const result = await bundle.write({
        file: 'bundle.js',
        format: 'cjs'
    })

    console.log(result.output[0].code)
}

build()
    .catch(ex => console.error(ex))
```

Error for test2:
```js
Error: 'C:\projects\rollup-plugin-node-resolve-bug\node_modules\core-js-pure\stable\instance\starts-with.js' is imported as an external by  C:\projects\rollup-plugin-node-resolve-bug\node_modules\core-js-pure\stable\instance\starts-with.js?commonjs-proxy, but is already an existing non-external module id.
    at error (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:5211:30)
    at ModuleLoader.fetchResolvedDependency (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18239:24)
    at C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18248:102
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18248:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18225:9)
    at async Promise.all (index 1)
    at async ModuleLoader.fetchStaticDependencies (C:\projects\rollup-plugin-node-resolve-bug\node_modules\rollup\dist\shared\rollup.js:18248:34)
    at async Promise.all (index 0) {
  code: 'INVALID_EXTERNAL_ID',
  watchFiles: [
    'C:\\projects\\rollup-plugin-node-resolve-bug\\test2\\app.js',
    'C:\\projects\\rollup-plugin-node-resolve-bug\\test2\\module.js',
    'C:\\projects\\rollup-plugin-node-resolve-bug\\node_modules\\@babel\\runtime-corejs3\\core-js-stable\\instance\\starts-with.js',
    'C:\\projects\\rollup-plugin-node-resolve-bug\\node_modules\\core-js-pure\\stable\\instance\\starts-with.js',
    '\u0000C:\\projects\\rollup-plugin-node-resolve-bug\\node_modules\\core-js-pure\\stable\\instance\\starts-with.js?commonjs-proxy'
  ]
}
```

### Additional Information
see also this not resolved bug: https://github.com/rollup/rollup-plugin-commonjs/issues/413

**Comment by shellscape** [comment]
Thanks for the issue. We'd welcome a pill request to resolve it.

**Comment by bhovhannes** [comment]
This is still an issue, was it closed by mistake?

**Comment by naio-labs** [comment]
This is indeed still an issue!

**Comment by TJKoury** [comment]
Still an issue.

**Comment by shellscape** [comment]
As the bot's message states: unless someone is willing to pick up this issue and submit a PR or continue triage, this will remain in a stale, closed state. Further "still an issue" replies don't provide value, so this issue will remain locked and closed until the community steps up to help resolve it, or maintainers are able to find time to address it.
