### ISSUE TITLE
typescript fails when compilerOptions are specified without using tsconfig.json

### ISSUE THREAD

**Issue by Samantha-uk** [rollup/plugins#735]
- Rollup Plugin Name: typescript
- Rollup Plugin Version: 8.1.0
- Rollup Version: 2.35.1
- Operating System (or Browser): Debian Buster
- Node Version: 14.15.1
- Link to reproduction: https://repl.it/@Samanthauk/rollup-plugin-repro

### Expected Behavior
Compilation to proceed as specified in the compilerOptions passed in to plugin-typescript.

### Actual Behavior
[!] (plugin typescript) Error: Could not load /home/runner/rollup-plugin-repro/input.ts: Debug Failure.

### Additional Information
The error appears to be caused by an assertion failing inside `ts.getOutputFileNames` expecting there to be a tsconfig.json path.

I'll submit a PR with a  test for this usecase (_skipped as the test currently fails_).

**Comment by Samantha-uk** [comment]
I updated my [reproduction](https://repl.it/@Samanthauk/rollup-plugin-repro) to use (_I believe_) the latest rollup/typescript plugin versions
I still get the same error message. :(
```
input.ts → output/bundle.js...
[!] (plugin typescript) Error: Could not load /home/runner/rollup-plugin-repro/input.ts: Debug Failure.
Error: Could not load /home/runner/rollup-plugin-repro/input.ts: Debug Failure.
    at rootDirOfOptions (/home/runner/rollup-plugin-repro/node_modules/typescript/lib/typescript.js:99520:75)
    at getOutputPathWithoutChangingExt (/home/runner/rollup-plugin-repro/node_modules/typescript/lib/typescript.js:99524:71)
    at getOutputDeclarationFileName (/home/runner/rollup-plugin-repro/node_modules/typescript/lib/typescript.js:99530:35)
    at getOwnOutputFileNames (/home/runner/rollup-plugin-repro/node_modules/typescript/lib/typescript.js:99577:23)
    at Object.getOutputFileNames (/home/runner/rollup-plugin-repro/node_modules/typescript/lib/typescript.js:99608:13)
    at findTypescriptOutput (/home/runner/rollup-plugin-repro/node_modules/@rollup/plugin-typescript/dist/index.js:435:33)
    at Object.load (/home/runner/rollup-plugin-repro/node_modules/@rollup/plugin-typescript/dist/index.js:741:28)

exit status 1
```

**Comment by shellscape** [comment]
I used your original reproduction and failing test to validate the work that closed this issue. Note that it hasn't been published. Between the open issue waiting on TS 4.2.0 and the update yesterday, your issue is addressed.

**Comment by Samantha-uk** [comment]
Thank you.
As it happens I modified the TS plugin and have been running it for several weeks without issue ... perhaps I'll PR it ...
