### ISSUE TITLE
Plugin alias struggling in combination with typescript

### ISSUE THREAD

**Issue by danimoh** [rollup/plugins#795]
- Rollup Plugin Name: @rollup/plugin-alias
- Rollup Plugin Version: 3.1.2
- Rollup Version: 2.38.5
- Operating System (or Browser): Linux
- Node Version:12.18.3
- Link to reproduction: https://repl.it/@danimoh/rollup-plugin-repro-alias

### Expected Behavior

There should be no difference between using absolute or relative paths with regards to other plugins.

### Actual Behavior

Builds correctly when using relative paths, fails when using an absolute path, although the file is correctly found.

### Additional Information

When switching the alias for the-answer in https://repl.it/@danimoh/rollup-plugin-repro-alias#rollup.config.js from `src/aliased-answer.ts` to `./aliased-answer.ts` processing the typescript file words, but not for `src/aliased-answer.ts` although the file is found, see the error that gets thrown in the repl:

```
[!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
src/aliased-answer.ts (1:12)
1: const answer: number = 1337;
               ^
2: export default answer;
Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
    at error (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:5239:30)
    at Module.error (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:9950:16)
    at tryParse (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:9809:23)
    at Module.setSource (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:10257:19)
    at ModuleLoader.addModuleSource (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:18542:20)
    at async ModuleLoader.fetchModule (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:18598:9)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchStaticDependencies (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:18623:34)
    at async Promise.all (index 0)
    at async ModuleLoader.fetchModule (/home/runner/rollup-plugin-repro-alias/node_modules/rollup/dist/shared/rollup.js:18600:9)
```

**Comment by shellscape** [comment]
Please include more information on your issue about the problem you're experiencing. Without more info it's unlikely anyone will take up your issue to triage.

**Comment by danimoh** [comment]
Hello shellscape.
It's essentially in the repl.
When switching the `alias` for `the-answer` in https://repl.it/@danimoh/rollup-plugin-repro-alias#rollup.config.js from `src/aliased-answer.ts` to `./aliased-answer.ts` it works, but not for `src/aliased-answer.ts` although the file is found.
I guess that's all I know.

**Comment by shellscape** [comment]
Would you be so kind as to place the error in code fences in the PR description?

**Comment by DominicTobias** [comment]
I tried appending `.tsx` to the virtual file but still thinks it's a JS file. Also no luck in a vanilla plugin. Did you figure it out?

**Comment by danimoh** [comment]
For me using a path relative to the file that imports the original file / package to be aliased worked.
E.g. if I'd want to shim an unnecessary dependency `unnecessary_dependency` of one of my depedencies located in `node_modules/my_dependency` to `src/shim.ts` I'd set the following alias:
```
alias({
    entries: {
        unnecessary_dependency: '../../src/lib/shim.ts',
    },
}),
```
