### ISSUE TITLE
@rollup/typescript: rollup output file, instead of dir: (plugin typescript) TypeError: The "from" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by btakita** [rollup/plugins#862]
Looks like the `rollup.config` `output.file` prop is not supported. Only `output.dir` is supported

https://github.com/rollup/plugins/blob/53776ee3fc59587fe5ff0c756216185f48372507/packages/typescript/src/index.ts#L153

Using `output.file` results in the following error:

```
[!] (plugin typescript) TypeError: The "from" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "from" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:329:5)
    at validateString (node:internal/validators:129:11)
    at Object.relative (node:path:1095:5)
    at Object.generateBundle (/project/path/node_modules/@rollup/plugin-typescript/dist/index.js:805:54)
    at /project/path/ui/node_modules/rollup/dist/shared/rollup.js:18765:25
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Comment by thien-do** [comment]
hm this is a really big issue :( (just tried to use this instead of the unofficial ts2 plugin)
