### ISSUE TITLE
Error: 'sample' is not exported by build/optimized.wasm, imported by src/index-mjs.js

### ISSUE THREAD

**Issue by xiaohk** [rollup/plugins#901]
Hello, I am trying to use the [wasm plugin](https://github.com/rollup/plugins/tree/master/packages/wasm) to bundle my Wasm file as a base64 string. However, I keep getting the error:

```
2: import { sample } from '../build/optimized.wasm';
            ^
3: 
4: export const testWASM = () => {
Error: 'sample' is not exported by build/optimized.wasm, imported by src/index-mjs.js
    at error (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:7917:30)
    at Module.error (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:9860:16)
    at Module.traceVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:10241:29)
    at ModuleScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:9018:39)
    at ReturnValueScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:3240:38)
    at ChildScope.findVariable (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:3240:38)
    at Identifier.bind (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:4169:40)
    at CallExpression.bind (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:2490:23)
    at CallExpression.bind (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:6589:15)
    at MemberExpression.bind (/usr/local/lib/node_modules/rollup/dist/shared/rollup.js:2490:23)
```

I follow the documentation of the wasm plugin to import the wasm file from my JS:

```js
import { sample } from '../build/optimized.wasm';

export const testWASM = () => {
  sample({}).then((result) => {
    console.log(result);
  });
};
```

Here is my rollup config file:

```js
import { nodeResolve } from '@rollup/plugin-node-resolve';
import { wasm } from '@rollup/plugin-wasm';

export default {
  input: 'src/index-mjs.js',
  output: {
    file: 'dist/mjs/index.js',
    format: 'es'
  },
  plugins: [
    wasm(),
    nodeResolve()
  ],
};
```

I am not really sure what I did wrong :(

**Comment by shellscape** [comment]
_If you are sure this is a bug or documentation issue, please take the time to refile this issue **using the issue template**._

Hey there, thanks for opening an issue - Unfortunately you missed (or may have disregarded) the message about issue templates being _required_. Because our issue template was removed, we assume that this is a support request, and that's not something we offer here. Also, if you refile, please don't ignore Issue sections. They're in the template because they're useful to the maintainers of this project.
